# Generated by Django 2.1 on 2020-02-05 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_problem_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='LogsSearchAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('branch_code', models.CharField(max_length=3)),
                ('search_by', models.CharField(max_length=25)),
                ('search_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'logs_search_access',
            },
        ),
        migrations.CreateModel(
            name='ProblemManagementHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_code', models.CharField(max_length=3)),
                ('ip', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=100)),
                ('search_by', models.CharField(max_length=25)),
                ('search_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'problem_management_history',
            },
        ),
        migrations.CreateModel(
            name='ProblemManagementHistoryRefundDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('history_id', models.PositiveIntegerField()),
                ('bank_id', models.PositiveIntegerField()),
                ('bank_location', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('refund_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'problem_management_history_refund_detail',
            },
        ),
        migrations.AlterIndexTogether(
            name='problemmanagementhistoryrefunddetail',
            index_together={('account_name', 'account_number', 'created_at')},
        ),
        migrations.AddIndex(
            model_name='problemmanagementhistory',
            index=models.Index(fields=['search_key'], name='problem_man_search__d7972d_idx'),
        ),
        migrations.AlterIndexTogether(
            name='problemmanagementhistory',
            index_together={('ip', 'created_at'), ('search_by', 'search_key', 'created_at'), ('ip', 'search_by', 'search_key', 'created_at')},
        ),
        migrations.AlterIndexTogether(
            name='logssearchaccess',
            index_together={('ip', 'created_at')},
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['name'], name='bank_name_daa2d3_idx'),
        ),
    ]
